clean:
	if [ -f parsetab.py ] ; then rm parsetab.py; fi
	if [ -f parsetab.pyc ] ; then rm parsetab.pyc; fi
	if [ -f scanner.pyc ] ; then rm scanner.pyc; fi
	if [ -f parser.out ] ; then rm parser.out; fi
	if [ -f ../tree ] ; then rm ../tree; fi